# Generated by Django 5.2.18 on 2026-10-09 10:36

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("deactivated", "Deactivated"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="staff status"),
                ),
                (
                    "is_active",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(status="active", then=models.Value(True)),
                            default=models.Value(False),
                        ),
                        output_field=models.BooleanField(),
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="last seen at"),
                ),
                (
                    "activated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="activated at"),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="deactivated at"),
                ),
                (
                    "anonymized_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="anonymized at"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ["last_name", "first_name"],
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=50, verbose_name="provider")),
                ("subject", models.CharField(max_length=255, verbose_name="subject")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "external identity",
                "verbose_name_plural": "external identities",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(blank=True, max_length=150, verbose_name="job title"),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                        verbose_name="bio",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="avatar",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Paris",
                        max_length=64,
                        validators=[accounts.models.validate_timezone],
                        verbose_name="time zone",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Automatic"),
                            ("en", "English"),
                            ("fr", "Français"),
                        ],
                        max_length=8,
                        verbose_name="language",
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("private", "Only me"),
                            ("communities", "Members of my communities"),
                            ("company", "Everyone in the company"),
                        ],
                        default="company",
                        max_length=20,
                        verbose_name="profile visibility",
                    ),
                ),
                (
                    "is_discoverable",
                    models.BooleanField(default=True, verbose_name="discoverable"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "interests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="profiles",
                        to="taxonomy.tag",
                        verbose_name="interests",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
            },
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="accounts_user_email_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(
                fields=("provider", "subject"),
                name="accounts_externalidentity_provider_subject_unique",
            ),
        ),
    ]
