# Generated by Django 5.2.18 on 2026-10-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_dataexport"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(
                fields=("user", "provider"),
                name="accounts_externalidentity_user_provider_unique",
            ),
        ),
    ]
