# Generated by Django 5.2.18 on 2026-10-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_externalidentity_user_provider_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_pending_key",
            field=models.CharField(blank=True, max_length=255, verbose_name="pending avatar key"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_scan_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("pending", "Being checked"),
                    ("infected", "Refused by the virus scan"),
                    ("error", "Check failed"),
                ],
                default="",
                max_length=16,
                verbose_name="avatar scan status",
            ),
        ),
    ]
