# Generated by Django 5.2.18 on 2026-10-09 14:58

import uuid

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import communities.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taxonomy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="people",
                        help_text="Bootstrap Icons name.",
                        max_length=64,
                        verbose_name="icon",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="order")),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "community category",
                "verbose_name_plural": "community categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="public ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=140, unique=True, verbose_name="slug"),
                ),
                ("tagline", models.CharField(max_length=160, verbose_name="tagline")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("rules", models.TextField(blank=True, verbose_name="rules")),
                ("objectives", models.TextField(blank=True, verbose_name="objectives")),
                (
                    "cover_image",
                    models.FileField(
                        blank=True,
                        upload_to="communities/covers/",
                        verbose_name="cover image",
                    ),
                ),
                (
                    "access_mode",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("request", "On request"),
                            ("invite", "Invitation only"),
                        ],
                        default="open",
                        max_length=16,
                        verbose_name="access mode",
                    ),
                ),
                (
                    "listed",
                    models.BooleanField(default=False, verbose_name="listed in the catalogue"),
                ),
                (
                    "allow_member_uploads",
                    models.BooleanField(default=False, verbose_name="members may upload files"),
                ),
                (
                    "require_post_review",
                    models.BooleanField(default=False, verbose_name="posts require review"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="archived at"),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True, verbose_name="search vector"
                    ),
                ),
                (
                    "member_count",
                    models.PositiveIntegerField(default=0, verbose_name="member count"),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="last activity"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="communities",
                        to="taxonomy.tag",
                        verbose_name="tags",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="communities",
                        to="communities.communitycategory",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "community",
                "verbose_name_plural": "communities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CommunityCreationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="public ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("justification", models.TextField(verbose_name="justification")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="decided at"),
                ),
                (
                    "decision_note",
                    models.TextField(blank=True, verbose_name="decision note"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="communities.communitycategory",
                        verbose_name="category",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="communities.community",
                        verbose_name="community",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="decided by",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_creation_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="requester",
                    ),
                ),
            ],
            options={
                "verbose_name": "community creation request",
                "verbose_name_plural": "community creation requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="public ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("contributor", "Contributor"),
                            ("expert", "Expert"),
                            ("moderator", "Moderator"),
                            ("animator", "Facilitator"),
                            ("owner", "Lead"),
                        ],
                        default="member",
                        max_length=16,
                        verbose_name="role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=communities.models._invitation_expiry,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="communities.community",
                        verbose_name="community",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invited by",
                    ),
                ),
                (
                    "invited_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invited user",
                    ),
                ),
            ],
            options={
                "verbose_name": "community invitation",
                "verbose_name_plural": "community invitations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("contributor", "Contributor"),
                            ("expert", "Expert"),
                            ("moderator", "Moderator"),
                            ("animator", "Facilitator"),
                            ("owner", "Lead"),
                        ],
                        default="member",
                        max_length=16,
                        verbose_name="role",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="joined at"
                    ),
                ),
                (
                    "notification_level",
                    models.CharField(
                        choices=[
                            ("all", "All activity"),
                            ("highlights", "Highlights"),
                            ("none", "None"),
                        ],
                        default="highlights",
                        max_length=16,
                        verbose_name="notification level",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="communities.community",
                        verbose_name="community",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "community membership",
                "verbose_name_plural": "community memberships",
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="MembershipRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="public ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, max_length=500, verbose_name="message"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="decided at"),
                ),
                (
                    "decision_note",
                    models.TextField(blank=True, verbose_name="decision note"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_requests",
                        to="communities.community",
                        verbose_name="community",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="decided by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_membership_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "membership request",
                "verbose_name_plural": "membership requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminAccessGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)],
                        verbose_name="reason",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=communities.models._admin_access_expiry,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_admin_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_access_grants",
                        to="communities.community",
                        verbose_name="community",
                    ),
                ),
            ],
            options={
                "verbose_name": "administrator access grant",
                "verbose_name_plural": "administrator access grants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["community", "user", "expires_at"],
                        name="admin_grant_lookup_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="community",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="community_search_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(fields=["category"], name="community_category_idx"),
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(fields=["access_mode"], name="community_access_mode_idx"),
        ),
        migrations.AddConstraint(
            model_name="community",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("status", "archived"), _negated=True),
                name="community_name_unique_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="communityinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("community", "invited_user"),
                name="one_pending_invitation",
            ),
        ),
        migrations.AddConstraint(
            model_name="communityinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("role", "owner"), _negated=True),
                name="invitation_role_below_owner",
            ),
        ),
        migrations.AddIndex(
            model_name="communitymembership",
            index=models.Index(fields=["user", "community"], name="membership_user_community_idx"),
        ),
        migrations.AddIndex(
            model_name="communitymembership",
            index=models.Index(fields=["community", "role"], name="membership_community_role_idx"),
        ),
        migrations.AddConstraint(
            model_name="communitymembership",
            constraint=models.UniqueConstraint(
                fields=("community", "user"), name="one_membership_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="membershiprequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("community", "user"),
                name="one_pending_request",
            ),
        ),
    ]
