# Generated by Django 5.2.18 on 2026-10-10 11:46

import uuid

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communities", "0002_seed_categories"),
        ("posts", "0001_initial"),
        ("taxonomy", "0002_tag_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="public ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, max_length=5000, verbose_name="description"),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("guide", "Guide"),
                            ("template", "Template"),
                            ("presentation", "Presentation"),
                            ("reference", "Reference"),
                            ("code_sample", "Code sample"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                        verbose_name="type",
                    ),
                ),
                (
                    "owner_display",
                    models.CharField(max_length=150, verbose_name="owner name"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("community", "Everyone who can read the community"),
                            ("restricted", "Members with a minimum role"),
                        ],
                        default="community",
                        max_length=16,
                        verbose_name="visibility",
                    ),
                ),
                (
                    "min_role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("contributor", "Contributor"),
                            ("expert", "Expert"),
                            ("moderator", "Moderator"),
                            ("animator", "Facilitator"),
                            ("owner", "Lead"),
                        ],
                        default="member",
                        max_length=16,
                        verbose_name="minimum role to read",
                    ),
                ),
                (
                    "download_min_role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("contributor", "Contributor"),
                            ("expert", "Expert"),
                            ("moderator", "Moderator"),
                            ("animator", "Facilitator"),
                            ("owner", "Lead"),
                        ],
                        default="member",
                        max_length=16,
                        verbose_name="minimum role to download",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="expires at"),
                ),
                (
                    "review_due_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="review due at"),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(default=0, verbose_name="download count"),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="archived at"),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True, verbose_name="search vector"
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="archived by",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="communities.community",
                        verbose_name="community",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documents",
                        to="taxonomy.tag",
                        verbose_name="tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
                "ordering": ["-updated_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="public ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="number")),
                (
                    "version_label",
                    models.CharField(max_length=40, verbose_name="version"),
                ),
                (
                    "storage_key",
                    models.CharField(blank=True, max_length=255, verbose_name="storage key"),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="file name"),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=127, verbose_name="content type"),
                ),
                ("size", models.PositiveBigIntegerField(verbose_name="size")),
                ("sha256", models.CharField(max_length=64, verbose_name="SHA-256")),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Scan in progress"),
                            ("clean", "Clean"),
                            ("infected", "Infected"),
                            ("error", "Scan failed"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="scan status",
                    ),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="scanned at"),
                ),
                (
                    "scan_detail",
                    models.CharField(blank=True, max_length=255, verbose_name="scan detail"),
                ),
                (
                    "change_note",
                    models.CharField(blank=True, max_length=500, verbose_name="change note"),
                ),
                (
                    "is_reference",
                    models.BooleanField(default=False, verbose_name="reference version"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "document version",
                "verbose_name_plural": "document versions",
                "ordering": ["-number"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.documentversion",
                verbose_name="reference version",
            ),
        ),
        migrations.CreateModel(
            name="DownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_preview",
                    models.BooleanField(default=False, verbose_name="preview"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_downloads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="documents.documentversion",
                        verbose_name="version",
                    ),
                ),
            ],
            options={
                "verbose_name": "download",
                "verbose_name_plural": "downloads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="documents.document",
                        verbose_name="document",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_links",
                        to="posts.post",
                        verbose_name="post",
                    ),
                ),
            ],
            options={
                "verbose_name": "document link",
                "verbose_name_plural": "document links",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("post__isnull", False)),
                        name="document_link_exactly_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("post__isnull", False)),
                        fields=("document", "post"),
                        name="document_link_unique_post",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                models.F("document"),
                models.OrderBy(models.F("created_at"), descending=True),
                name="version_document_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                condition=models.Q(("scan_status", "clean"), _negated=True),
                fields=["scan_status", "created_at"],
                name="version_scan_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "number"), name="version_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_reference", True)),
                fields=("document",),
                name="version_one_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("storage_key", ""), _negated=True),
                fields=("storage_key",),
                name="version_storage_key_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["community", "doc_type"], name="document_community_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                models.F("community"),
                models.F("status"),
                models.OrderBy(models.F("updated_at"), descending=True),
                name="document_list_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False), ("status", "active")),
                fields=["expires_at"],
                name="document_expiry_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="document_search_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="downloadlog",
            index=models.Index(
                models.F("document"),
                models.OrderBy(models.F("created_at"), descending=True),
                name="download_document_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="downloadlog",
            index=models.Index(fields=["created_at"], name="download_created_idx"),
        ),
    ]
