# Generated by Django 5.2.18 on 2026-10-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="promote_on_clean",
            field=models.BooleanField(default=False, verbose_name="make reference once clean"),
        ),
    ]
