from base64 import b32encode
from urllib.parse import quote

import segno
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.db import transaction
from django.shortcuts import redirect, render, resolve_url
from django.urls import reverse
from django.utils.http import url_has_allowed_host_and_scheme
from django.utils.safestring import mark_safe
from django.utils.translation import gettext as _
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django_otp import devices_for_user
from django_otp import login as otp_login
from django_otp.plugins.otp_totp.models import TOTPDevice

from audit.services import record
from core.views_errors import too_many_requests

from .forms import OTPTokenForm
from .policies import has_confirmed_device


def _next_url(request) -> str:
    candidate = request.POST.get("next") or request.GET.get("next", "")
    if url_has_allowed_host_and_scheme(
        candidate, allowed_hosts={request.get_host()}, require_https=request.is_secure()
    ):
        return candidate
    return resolve_url(settings.LOGIN_REDIRECT_URL)


def _redirect_with_next(name: str, next_url: str):
    return redirect(f"{reverse(name)}?next={quote(next_url)}")


# Failed codes are counted per user in a fixed window, whichever MFA form they come from.
def _failures_key(user) -> str:
    return f"mfa-failures:{user.pk}"


def _rate_limited(user) -> bool:
    return cache.get(_failures_key(user), 0) >= settings.MFA_MAX_FAILURES


def _record_failure(user) -> None:
    key = _failures_key(user)
    cache.add(key, 0, timeout=int(settings.MFA_FAILURE_WINDOW.total_seconds()))
    try:
        cache.incr(key)
    except ValueError:  # Expired between add() and incr().
        cache.set(key, 1, timeout=int(settings.MFA_FAILURE_WINDOW.total_seconds()))


def _qr_svg(device: TOTPDevice) -> str:
    qr = segno.make(device.config_url, error="m")
    svg = qr.svg_inline(scale=4, border=2, light="#fff", title=_("QR code"))
    # Safe: markup generated by segno; the provisioning URI is only encoded as modules.
    return mark_safe(svg)  # noqa: S308  # nosec B308 B703


@sensitive_post_parameters("otp_token")
@never_cache
@login_required
def mfa_setup(request):
    """Enrol a TOTP authenticator: show its QR code, confirm it with a first code."""
    user = request.user
    next_url = _next_url(request)
    if user.is_verified():
        return redirect(next_url)
    if has_confirmed_device(user):
        return _redirect_with_next("accounts:mfa_verify", next_url)
    # Reuse the pending device so that reloading the page keeps the same secret.
    device = TOTPDevice.objects.filter(user=user, confirmed=False).order_by(
        "pk"
    ).first() or TOTPDevice.objects.create(user=user, name="default", confirmed=False)
    form = OTPTokenForm(request.POST or None)
    if request.method == "POST":
        if _rate_limited(user):
            return too_many_requests(request)
        if form.is_valid() and device.verify_token(form.cleaned_data["otp_token"]):
            with transaction.atomic():
                device.confirmed = True
                device.save(update_fields=["confirmed"])
                record(
                    actor=user,
                    action="auth.mfa_enrolled",
                    target=user,
                    changes={"device_type": "totp"},
                )
            otp_login(request, device)
            cache.delete(_failures_key(user))
            return redirect(next_url)
        _record_failure(user)
        form.reject()
    context = {
        "form": form,
        "next": next_url,
        "qr_svg": _qr_svg(device),
        "secret": b32encode(device.bin_key).decode(),
    }
    return render(request, "accounts/mfa_setup.html", context)


@sensitive_post_parameters("otp_token")
@never_cache
@login_required
def mfa_verify(request):
    """Ask for a code from the user's confirmed authenticator to verify the session."""
    user = request.user
    next_url = _next_url(request)
    if user.is_verified():
        return redirect(next_url)
    if not has_confirmed_device(user):
        return _redirect_with_next("accounts:mfa_setup", next_url)
    form = OTPTokenForm(request.POST or None)
    if request.method == "POST":
        if _rate_limited(user):
            return too_many_requests(request)
        device = None
        if form.is_valid():
            device = _matching_device(user, form.cleaned_data["otp_token"])
        if device is not None:
            otp_login(request, device)
            record(actor=user, action="auth.mfa_verified", target=user)
            cache.delete(_failures_key(user))
            return redirect(next_url)
        _record_failure(user)
        form.reject()
    return render(request, "accounts/mfa_verify.html", {"form": form, "next": next_url})


def _matching_device(user, token: str):
    """Verify ``token`` against each confirmed device (each applies its own throttling)."""
    with transaction.atomic():
        for device in devices_for_user(user, confirmed=True, for_verify=True):
            if device.verify_token(token):
                return device
    return None
