# Generated by Django 5.2.18 on 2026-10-09 16:52

import uuid

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communities", "0002_seed_categories"),
        ("taxonomy", "0002_tag_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookmarkCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="public ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmark_collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "bookmark collection",
                "verbose_name_plural": "bookmark collections",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="public ID",
                    ),
                ),
                (
                    "author_display",
                    models.CharField(max_length=150, verbose_name="author name"),
                ),
                (
                    "body",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(10000)],
                        verbose_name="body",
                    ),
                ),
                (
                    "body_html",
                    models.TextField(blank=True, verbose_name="rendered body"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("visible", "Visible"), ("hidden", "Hidden")],
                        default="visible",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_expert_answer",
                    models.BooleanField(default=False, verbose_name="expert answer"),
                ),
                (
                    "hidden_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="hidden at"),
                ),
                (
                    "hidden_reason",
                    models.TextField(blank=True, verbose_name="reason for hiding"),
                ),
                (
                    "reaction_counts",
                    models.JSONField(blank=True, default=dict, verbose_name="reaction counts"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "hidden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="hidden by",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replies",
                        to="posts.comment",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="public ID",
                    ),
                ),
                (
                    "author_display",
                    models.CharField(max_length=150, verbose_name="author name"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("discussion", "Discussion"),
                            ("question", "Question"),
                            ("announcement", "Announcement"),
                            ("article", "Article"),
                        ],
                        default="discussion",
                        max_length=16,
                        verbose_name="kind",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "body",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(50000)],
                        verbose_name="body",
                    ),
                ),
                (
                    "body_html",
                    models.TextField(blank=True, verbose_name="rendered body"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending review"),
                            ("published", "Published"),
                            ("hidden", "Hidden"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="published at"),
                ),
                (
                    "pinned_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="pinned at"),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="last activity"
                    ),
                ),
                (
                    "comment_count",
                    models.PositiveIntegerField(default=0, verbose_name="comment count"),
                ),
                (
                    "reaction_counts",
                    models.JSONField(blank=True, default=dict, verbose_name="reaction counts"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="version"),
                ),
                (
                    "hidden_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="hidden at"),
                ),
                (
                    "hidden_reason",
                    models.TextField(blank=True, verbose_name="reason for hiding"),
                ),
                (
                    "status_before_hidden",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending review"),
                            ("published", "Published"),
                            ("hidden", "Hidden"),
                            ("archived", "Archived"),
                        ],
                        max_length=16,
                        verbose_name="status before hiding",
                    ),
                ),
                (
                    "review_note",
                    models.TextField(blank=True, verbose_name="review note"),
                ),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="archived at"),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True, verbose_name="search vector"
                    ),
                ),
                (
                    "accepted_answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="posts.comment",
                        verbose_name="accepted answer",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="communities.community",
                        verbose_name="community",
                    ),
                ),
                (
                    "hidden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="hidden by",
                    ),
                ),
                (
                    "pinned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="pinned by",
                    ),
                ),
                (
                    "shared_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shares",
                        to="posts.post",
                        verbose_name="shared from",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posts",
                        to="taxonomy.tag",
                        verbose_name="tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
                "ordering": ["-last_activity_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Mention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="posts.comment",
                        verbose_name="comment",
                    ),
                ),
                (
                    "mentioned_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mentioned user",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="posts.post",
                        verbose_name="post",
                    ),
                ),
            ],
            options={
                "verbose_name": "mention",
                "verbose_name_plural": "mentions",
            },
        ),
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="public ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("inappropriate", "Inappropriate content"),
                            ("confidential", "Confidential information"),
                            ("outdated", "Outdated information"),
                            ("spam", "Spam"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                        verbose_name="reason",
                    ),
                ),
                (
                    "details",
                    models.TextField(blank=True, max_length=2000, verbose_name="details"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "handled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="handled at"),
                ),
                (
                    "resolution_note",
                    models.TextField(blank=True, verbose_name="resolution note"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="posts.comment",
                        verbose_name="comment",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_reports",
                        to="communities.community",
                        verbose_name="community",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="handled by",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reporter",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="posts.post",
                        verbose_name="post",
                    ),
                ),
            ],
            options={
                "verbose_name": "content report",
                "verbose_name_plural": "content reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comments",
                to="posts.post",
                verbose_name="post",
            ),
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookmarks",
                        to="posts.bookmarkcollection",
                        verbose_name="collection",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="posts.post",
                        verbose_name="post",
                    ),
                ),
            ],
            options={
                "verbose_name": "bookmark",
                "verbose_name_plural": "bookmarks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="editor",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="posts.post",
                        verbose_name="post",
                    ),
                ),
            ],
            options={
                "verbose_name": "post revision",
                "verbose_name_plural": "post revisions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("useful", "Useful"),
                            ("thanks", "Thanks"),
                            ("insightful", "Insightful"),
                        ],
                        max_length=16,
                        verbose_name="kind",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="posts.comment",
                        verbose_name="comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="posts.post",
                        verbose_name="post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "reaction",
                "verbose_name_plural": "reactions",
            },
        ),
        migrations.AddConstraint(
            model_name="bookmarkcollection",
            constraint=models.UniqueConstraint(
                models.F("user"),
                django.db.models.functions.text.Lower("name"),
                name="bookmark_collection_name_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                models.F("community"),
                models.F("status"),
                models.OrderBy(models.F("last_activity_at"), descending=True),
                name="post_feed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                condition=models.Q(("pinned_at__isnull", False)),
                fields=["community", "pinned_at"],
                name="post_pinned_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                models.F("author"),
                models.OrderBy(models.F("created_at"), descending=True),
                name="post_author_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="post_search_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("accepted_answer__isnull", True),
                    ("kind", "question"),
                    _connector="OR",
                ),
                name="post_accepted_answer_only_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="mention",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("post__isnull", False), ("comment__isnull", True)),
                    models.Q(("comment__isnull", False), ("post__isnull", True)),
                    _connector="OR",
                ),
                name="mention_exactly_one_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="mention",
            constraint=models.UniqueConstraint(
                condition=models.Q(("post__isnull", False)),
                fields=("post", "mentioned_user"),
                name="mention_unique_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="mention",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comment__isnull", False)),
                fields=("comment", "mentioned_user"),
                name="mention_unique_comment",
            ),
        ),
        migrations.AddIndex(
            model_name="contentreport",
            index=models.Index(
                fields=["community", "status", "created_at"], name="report_queue_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("post__isnull", False), ("comment__isnull", True)),
                    models.Q(("comment__isnull", False), ("post__isnull", True)),
                    _connector="OR",
                ),
                name="report_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("post__isnull", False), ("status", "open")),
                fields=("reporter", "post"),
                name="one_open_report_per_target_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comment__isnull", False), ("status", "open")),
                fields=("reporter", "comment"),
                name="one_open_report_per_target_comment",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["post", "parent", "created_at"], name="comment_thread_idx"),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.CheckConstraint(
                condition=models.Q(("post__isnull", False)),
                name="bookmark_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(("post__isnull", False)),
                fields=("user", "post"),
                name="bookmark_unique_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("post__isnull", False), ("comment__isnull", True)),
                    models.Q(("comment__isnull", False), ("post__isnull", True)),
                    _connector="OR",
                ),
                name="reaction_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("post__isnull", False)),
                fields=("user", "post", "kind"),
                name="reaction_unique_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comment__isnull", False)),
                fields=("user", "comment", "kind"),
                name="reaction_unique_comment",
            ),
        ),
    ]
