# Generated by Django 5.2.18 on 2026-10-10 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communities", "0002_seed_categories"),
        ("documents", "0001_initial"),
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookmark",
            name="bookmark_exactly_one_target",
        ),
        migrations.RemoveConstraint(
            model_name="contentreport",
            name="report_exactly_one_target",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="documents.document",
                verbose_name="document",
            ),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="documents.document",
                verbose_name="document",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("post__isnull", False), ("document__isnull", True)),
                    models.Q(("document__isnull", False), ("post__isnull", True)),
                    _connector="OR",
                ),
                name="bookmark_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(("document__isnull", False)),
                fields=("user", "document"),
                name="bookmark_unique_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("post__isnull", False),
                        ("comment__isnull", True),
                        ("document__isnull", True),
                    ),
                    models.Q(
                        ("comment__isnull", False),
                        ("post__isnull", True),
                        ("document__isnull", True),
                    ),
                    models.Q(
                        ("document__isnull", False),
                        ("post__isnull", True),
                        ("comment__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="report_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("document__isnull", False), ("status", "open")),
                fields=("reporter", "document"),
                name="one_open_report_per_target_document",
            ),
        ),
    ]
