# Generated by Django 5.2.18 on 2026-10-09 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(db_index=True, max_length=64, verbose_name="action"),
                ),
                (
                    "target_type",
                    models.CharField(max_length=64, verbose_name="target type"),
                ),
                (
                    "target_id",
                    models.CharField(max_length=64, verbose_name="target identifier"),
                ),
                (
                    "community_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="community identifier"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(blank=True, default=dict, verbose_name="changes"),
                ),
                (
                    "ip_hash",
                    models.CharField(blank=True, max_length=64, verbose_name="IP hash"),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, max_length=64, verbose_name="request identifier"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="created at",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit event",
                "verbose_name_plural": "audit events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_audit_target__59bbff_idx",
                    )
                ],
            },
        ),
    ]
